import json
from dotenv import load_dotenv

# LLM and Console Management
from llm.colibri_llm_stream import ColibriLLMStream
from manager.rich_console_manager import RichConsoleManager

# Session Management
from session.simple_session_manager import SimpleSessionManager, get_phase_trigger

# Tools and Schemas
from tool.schemas import AVAILABLE_TOOLS
from tool.file_tools import write_file, read_file, append_to_file
from tool.cmd_tools import execute_command

# Dynamic mapping of tool names to their python functions
TOOL_MAP = {
    "write_file": write_file,
    "read_file": read_file,
    "append_to_file": append_to_file,
    "execute_command": execute_command
}


def main():
    # 1. Initialization
    load_dotenv()
    llm = ColibriLLMStream()
    console = RichConsoleManager()

    console.display_system("Welcome to Just Finish It - Generic Autonomous Mode 🤖")

    # 2. Gather Initial User Input
    session_name = console.get_user_input("Please enter a session name to begin: ")
    initial_goal = console.get_user_input("\nWhat is your goal? (Be as detailed as possible): ")

    # Initialize Session Manager
    ssm = SimpleSessionManager(console, session_name)

    # 3. Define the strict sequence of phases
    PHASES = ["planner", "imp", "testing", "reviewer"]

    is_first_run = True

    # 4. Outer Loop for Re-runs and Feedback
    while True:
        if not is_first_run:
            console.display_system("\n==========================================")
            console.display_system(" ⏸️  PIPELINE COMPLETE - WAITING FOR FEEDBACK")
            console.display_system("==========================================")

            feedback = console.get_user_input(
                "\nDo you want to change anything in the plan, implementation, or tests? (Type your feedback, or 'exit'/'done' to quit): ")

            if feedback.strip().lower() in ['exit', 'done', 'quit', 'no', 'nothing']:
                break

            # Inject the feedback into the history before re-running the pipeline
            ssm.add_message("user",
                            f"USER FEEDBACK FOR ITERATION:\n{feedback}\n\nPlease re-evaluate and update the plan, then execute the implementation and tests to satisfy these new changes.")

        is_first_run = False

        # 5. Main Autonomous Pipeline
        for phase in PHASES:
            console.display_system(f"\n==========================================")
            console.display_system(f"   STARTING PHASE: {phase.upper()}")
            console.display_system(f"==========================================\n")

            # Inject the starting prompt for this specific phase
            trigger_message = get_phase_trigger(phase, initial_goal)
            ssm.add_message("user", trigger_message)

            # The AI must output this exact phrase to break the loop and move to the next phase
            completion_keyword = f"{phase.upper()}_COMPLETE"

            # 6. Continuous Tool Execution Loop for the current phase
            while True:
                # Call the LLM with the available tools
                response = llm.send_message(ssm.get_messages(phase), tools=AVAILABLE_TOOLS)
                parsed_response = console.print_agent_response(response)

                content = parsed_response.get("content")
                tool_calls = parsed_response.get("tool_calls")

                # Reconstruct and save the assistant's raw message to history
                assistant_message = {"role": "assistant"}
                if content:
                    assistant_message["content"] = content
                if tool_calls:
                    assistant_message["tool_calls"] = tool_calls

                # Use append_raw so the Pickle file saves correctly
                ssm.append_raw(assistant_message)

                # --- HANDLE TOOL CALLS ---
                if tool_calls:
                    for tc in tool_calls:
                        func_name = tc["function"]["name"]
                        args_str = tc["function"]["arguments"]
                        tc_id = tc["id"]

                        console.display_system(f"\n⚙️ Executing Tool: {func_name}")

                        try:
                            # Parse the JSON arguments generated by the AI
                            args = json.loads(args_str)
                            # Execute the dynamically mapped tool
                            tool_result = TOOL_MAP[func_name](**args)

                        except json.JSONDecodeError as e:
                            # CRITICAL FIX 1: Teach the AI how to recover
                            tool_result = (
                                f"JSON parsing failed: {str(e)}. "
                                "You attempted to output too much text at once, causing a truncation error. "
                                "Please write to the file in smaller chunks using the append_to_file tool."
                            )
                            # CRITICAL FIX 2: Sanitize the broken JSON in the history so the server doesn't crash (Error 500)
                            tc["function"]["arguments"] = json.dumps(
                                {"error": "malformed json stripped to prevent server crash"})
                            ssm.save_history()  # Update the pickle file with the sanitized JSON

                        except Exception as e:
                            tool_result = f"Error executing tool {func_name}: {str(e)}"

                        console.display_system(f"Result: {tool_result}")

                        # Append the tool's result to the history so the AI can evaluate it
                        ssm.append_raw({
                            "role": "tool",
                            "tool_call_id": tc_id,
                            "name": func_name,
                            "content": str(tool_result)
                        })

                    # Restart the loop to feed the tool results back to the LLM immediately
                    continue

                # --- CHECK FOR COMPLETION ---
                if content and completion_keyword in content:
                    console.display_system(f"\n✅ Phase '{phase}' completed successfully.")

                    # Special hook for planner phase to save the markdown file locally
                    if phase == "planner":
                        ssm.generate_plan_markdown()

                    break  # Exit the while loop and advance to the next phase

                # --- AUTO-NUDGE (STALL PREVENTION) ---
                # If the AI didn't call a tool and didn't output the completion keyword, nudge it.
                if not tool_calls and completion_keyword not in (content or ""):
                    ssm.add_message("user",
                                    f"Please continue your work. Remember, when you are entirely finished with this phase, you MUST output the exact phrase: '{completion_keyword}'.")

    # 7. Final Exit
    console.display_system("\n==========================================")
    console.display_system(" 🎉 JUST FINISH IT - SESSION TERMINATED 🎉")
    console.display_system("==========================================")


if __name__ == "__main__":
    main()