"""Standalone .sh generation for shbuild (step 3.3).

:func:`generate` turns a staged payload directory into the final deliverable:
a single executable POSIX ``sh`` script that embeds the whole payload (venv +
app sources + lock file + manifest) as base64 chunks and knows how to run it
with zero external state.

Runtime behaviour of the generated script (see :data:`WRAPPER_TEMPLATE`):

  * ``#!/bin/sh``, ``set -eu``; only POSIX constructs are used so dash, bash,
    ksh93 and busybox sh all work.
  * The payload archive is decoded from the embedded base64 stream into a
    temp file, its SHA-256 is verified against an embedded checksum (using
    whichever of sha256sum/shasum/openssl/python3 happens to be installed),
    and only then is it extracted.
  * Extraction goes to a per-build cache dir: the fixed ``--cache-dir`` baked
    in at build time, else ``$XDG_CACHE_HOME/shbuild/<name>``, else
    ``$HOME/.cache/shbuild/<name>`` (with a temp-dir fallback when HOME is
    unset).  If the payload already exists there *and* its marker file carries
    the same SHA-256, extraction is skipped entirely (cache hit); repeated
    runs are therefore cheap and silent.
  * ``--clear-cache`` forces re-extraction; every other argument is passed
    through verbatim to the entry script's ``$@``.

The template uses only single placeholders of the form ``__NAME__`` so it can
be filled with a plain :meth:`str.replace` chain (no brace escaping needed).
"""

from __future__ import annotations

import hashlib
import io
import stat
import tarfile
from dataclasses import dataclass, field
from pathlib import Path

from .builder import BuildResult, b64_chunks
from .config import BuildConfig


@dataclass
class ShSummary:
    """Facts about a generated script, for the CLI's build summary (step 3.4)."""

    out: Path
    payload_size_bytes: int = 0
    script_size_bytes: int = 0
    sha256: str = ""
    source_files: int = 0
    deps_installed: list[str] = field(default_factory=list)
    python_version: str = ""


def _deterministic_tar(payload_dir: Path, archive_path: Path) -> None:
    """Pack *payload_dir* into a reproducible tar.gz at *archive_path*.

    Entries are added in sorted order with fixed uid/gid/uname/gname/mtime so
    that the same payload always yields byte-identical archives; that
    stability is what lets the embedded SHA-256 act as a permanent content
    fingerprint.
    """
    fixed_mtime = 0

    members: list[tuple[str, Path]] = []

    def collect(directory: Path, prefix: str) -> None:
        for entry in sorted(directory.iterdir(), key=lambda p: p.name):
            rel = f"{prefix}/{entry.name}" if prefix else entry.name
            members.append((rel, entry))
            if entry.is_dir():
                collect(entry, rel)

    collect(payload_dir, "")

    # Build the tar.gz in memory so the gzip header (mtime=0, no original
    # filename) is fixed and the archive bytes depend only on payload content —
    # never on where/when we write it.  Wrap the gzip layer by hand because a
    # bare ``w:gz`` would embed the current time in the gzip header.
    import gzip

    buf = io.BytesIO()
    gz = gzip.GzipFile(fileobj=buf, mode="wb", mtime=fixed_mtime)
    with tarfile.open(fileobj=gz, mode="w") as tf:
        for rel, entry in sorted(members, key=lambda m: m[0]):
            info = tf.gettarinfo(str(entry), arcname=rel)
            info.uid = 0
            info.gid = 0
            info.uname = "shbuild"
            info.gname = "shbuild"
            info.mtime = fixed_mtime
            if entry.is_dir():
                info.type = tarfile.DIRTYPE
                tf.addfile(info)
            elif entry.is_symlink():
                tf.addfile(info)  # symlink: no fileobj needed, linkname preserved
            else:
                with open(entry, "rb") as fh:
                    tf.addfile(info, fh)
    gz.close()

    archive_path.write_bytes(buf.getvalue())


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


#: POSIX sh wrapper.  Placeholders (all ``__UPPER__``):
#:   __NAME__, __ENTRY__, __PYTHON_VERSION__, __DEPS_LIST__,
#:   __CACHE_DIR_EXPR__, __SHA256__, __B64_CHUNKS__
WRAPPER_TEMPLATE = r"""#!/bin/sh
# ---------------------------------------------------------------------------
# Generated by shbuild.  Standalone launcher for "__NAME__" (Python __PYTHON_VERSION__).
# Entry point: __ENTRY__
# Payload SHA-256: __SHA256__
# Deps baked in: __DEPS_LIST__
#
# Usage: ./script.sh [args...]            # args are passed to the entry script
#         ./script.sh --clear-cache ...   # force re-extraction, then run
# ---------------------------------------------------------------------------
set -eu

NAME="__NAME__"
ENTRY="__ENTRY__"
SHA256="__SHA256__"
CACHE_DIR_EXPR="__CACHE_DIR_EXPR__"

CLEAR_CACHE=0
VERBOSE=0
# Flags may appear before the entry script's arguments; anything else is left
# in "$@" untouched so it reaches the app verbatim.
while [ $# -gt 0 ]; do
    case "$1" in
        --clear-cache) CLEAR_CACHE=1; shift ;;
        --verbose|-v)  VERBOSE=1; shift ;;
        *) break ;;
    esac
done

# --- resolve the payload cache directory ------------------------------------
if [ -n "$CACHE_DIR_EXPR" ]; then
    CACHE_ROOT="$CACHE_DIR_EXPR"
else
    if [ -n "${XDG_CACHE_HOME:-}" ]; then
        CACHE_ROOT="${XDG_CACHE_HOME}/shbuild/${NAME}"
    elif [ -n "${HOME:-}" ]; then
        CACHE_ROOT="${HOME}/.cache/shbuild/${NAME}"
    else
        # No HOME/XDG: keep the payload in a private temp dir for this run.
        CACHE_ROOT="$(mktemp -d 2>/dev/null || echo "/tmp/shbuild-${NAME}")/shbuild"
    fi
fi

PAYLOAD_DIR="$CACHE_ROOT/payload"
MARKER_FILE="$PAYLOAD_DIR/.shbuild-sha"

# --- SHA-256 helper (uses the first tool available) --------------------------
sha256_of() {
    # $1 = file; prints lowercase hex digest or returns non-zero.
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1 && shasum --help 2>&1 | grep -q 'sha256'; then
        shasum -a 256 "$1" | awk '{print $1}'
    elif command -v openssl >/dev/null 2>&1; then
        openssl dgst -sha256 "$1" | awk '{print $NF}'
    else
        # Last resort: the payload's own python (already extracted).
        "${PAYLOAD_DIR}/venv/bin/python" -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$1"
    fi
}

# --- embedded base64 payload -------------------------------------------------
B64_CHUNKS='__B64_CHUNKS__'

have_payload() {
    [ -f "$MARKER_FILE" ] || return 1
    [ "$(cat "$MARKER_FILE")" = "$SHA256" ] || return 1
    [ -d "${PAYLOAD_DIR}/venv/bin" ] || return 1
    [ -f "${PAYLOAD_DIR}/${ENTRY}" ] || return 1
    return 0
}

extract_payload() {
    # Decode to a private temp file, verify checksum, then extract atomically.
    TMP_DIR="$(mktemp -d)"
    trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM
    ARCHIVE="$TMP_DIR/payload.tar.gz"
    printf '%s' "$B64_CHUNKS" | base64 -d > "$ARCHIVE" 2>/dev/null \
        || { echo "shbuild: error: decoding embedded payload failed (base64 not found?)" >&2; exit 1; }

    ACTUAL="$(sha256_of "$ARCHIVE")"
    if [ "$ACTUAL" != "$SHA256" ]; then
        echo "shbuild: error: payload checksum mismatch" >&2
        echo "  expected: $SHA256" >&2
        echo "  actual:   $ACTUAL" >&2
        exit 1
    fi

    STAGE_DIR="$TMP_DIR/stage"
    mkdir -p "$STAGE_DIR"
    tar -xzf "$ARCHIVE" -C "$STAGE_DIR"
    if [ ! -d "${STAGE_DIR}/venv/bin" ] || [ ! -f "${STAGE_DIR}/${ENTRY}" ]; then
        echo "shbuild: error: payload archive is missing venv or entry point" >&2
        exit 1
    fi

    mkdir -p "$(dirname "$PAYLOAD_DIR")"
    rm -rf "$PAYLOAD_DIR"
    mv "$STAGE_DIR" "$PAYLOAD_DIR"
    chmod +x "${PAYLOAD_DIR}/venv/bin/python"* 2>/dev/null || true
    printf '%s' "$SHA256" > "$MARKER_FILE"
    trap - EXIT HUP INT TERM
}

# --- main --------------------------------------------------------------------
if [ "$CLEAR_CACHE" = "1" ]; then
    rm -rf "$PAYLOAD_DIR"
fi

if have_payload; then
    if [ "$VERBOSE" = "1" ]; then
        echo "shbuild: cache hit — payload already extracted, skipping (sha=$SHA256)" >&2
    fi
else
    extract_payload
    if [ "$VERBOSE" = "1" ]; then
        echo "shbuild: payload extracted to $PAYLOAD_DIR" >&2
    fi
fi

PY="${PAYLOAD_DIR}/venv/bin/python"
[ -x "$PY" ] || { echo "shbuild: error: interpreter not found at $PY" >&2; exit 1; }

exec "$PY" "${PAYLOAD_DIR}/${ENTRY}" "$@"
"""


def _shell_quote(value: str) -> str:
    """Quote *value* for safe inclusion inside a double-quoted shell string."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def generate(
    config: BuildConfig,
    staging_dir: Path,
    result: BuildResult,
) -> ShSummary:
    """Produce the standalone .sh script at ``config.out``.

    Steps: pack *staging_dir* into a deterministic tar.gz, base64-chunk it,
    fill :data:`WRAPPER_TEMPLATE`, write the file and make it executable.
    Returns an :class:`ShSummary` the CLI uses for its build summary (3.4).
    """
    archive_path = staging_dir / ".payload.tar.gz"
    _deterministic_tar(staging_dir, archive_path)
    archive_bytes = archive_path.read_bytes()
    digest = _sha256_hex(archive_bytes)

    import json

    # Entry path as stored in the payload (root-relative POSIX under app/).
    entry_in_payload = f"app/{result.entry.name}"
    manifest_path = staging_dir / "MANIFEST.json"
    if manifest_path.exists():
        entry_rel = json.loads(manifest_path.read_text(encoding="utf-8")).get("entry")
        if entry_rel:
            entry_in_payload = f"app/{entry_rel}"

    # The base64 stream lives inside single quotes in the template; escape any
    # stray single quote (impossible for pure base64, but stay correct).
    chunks_stream = "".join(b64_chunks(archive_bytes))
    b64_embedded = chunks_stream.replace("'", "'\\''")

    deps_list = ", ".join(result.deps_installed) if result.deps_installed else "(none)"

    script_text = (
        WRAPPER_TEMPLATE.replace("__NAME__", _shell_quote(config.name))
        .replace("__ENTRY__", entry_in_payload or f"app/{result.entry.name}")
        .replace("__PYTHON_VERSION__", result.python_version)
        .replace("__DEPS_LIST__", deps_list)
        .replace("__CACHE_DIR_EXPR__", config.cache_dir or "")
        .replace("__SHA256__", digest)
        .replace("__B64_CHUNKS__", b64_embedded)
    )

    out = config.out
    if out.parent and not out.exists():
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script_text + "\n" if not script_text.endswith("\n") else script_text, encoding="utf-8")
    st = out.stat()
    mode = st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    out.chmod(mode)

    return ShSummary(
        out=out,
        payload_size_bytes=result.payload_size_bytes,
        script_size_bytes=out.stat().st_size,
        sha256=digest,
        source_files=result.source_files,
        deps_installed=list(result.deps_installed),
        python_version=result.python_version,
    )
