"""Dependency resolution, locking and offline wheel bundling for shbuild.

This module covers two related jobs at build time:

1. **Locking** — after dependencies have been installed into the baked venv we
   snapshot exactly what got installed (``pip freeze``) into a
   ``requirements.lock`` file. That lock file is stored inside the payload so
   the generated .sh can report/verify its dependency set at runtime and it
   gives reproducible rebuilds a stable, auditable record.

2. **Wheelhouse** (optional) — in fallback mode we additionally download
   prebuilt wheels for every resolved requirement into a ``wheelhouse/``
   directory inside the payload. The generated .sh can then run an offline
   ``pip install --no-index`` from that wheelhouse on first extraction, which
   is useful when a dependency has C extensions or otherwise should be
   (re)installed at runtime instead of being baked into the venv directly.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class WheelhouseInfo:
    """Result of resolving dependencies for a build."""

    lock_path: Path  # requirements.lock written inside the payload staging dir
    wheelhouse_dir: Path | None = None  # staged wheels/ dir (fallback mode only)
    locked_requirements: list[str] = field(default_factory=list)
    wheels: list[Path] = field(default_factory=list)


def _venv_python(venv_root: Path, version: str) -> str:
    return str(venv_root / "bin" / f"python{version}")


def write_lock_file(staging_dir: Path, venv_root: Path, version: str) -> tuple[Path, list[str]]:
    """Snapshot the installed distributions of *venv_root* into requirements.lock.

    The lock file is written to ``staging_dir/requirements.lock`` (i.e. it ends
    up inside the payload). pip's own metadata lines and our shbuild banner are
    excluded so the lock contains only the project's declared dependency tree.

    Returns:
        A ``(lock_path, requirements)`` tuple where *requirements* is the list
        of pinned ``name==version`` strings (empty entries removed).
    """
    staging_dir.mkdir(parents=True, exist_ok=True)
    lock_path = staging_dir / "requirements.lock"

    proc = subprocess.run(
        [_venv_python(venv_root, version), "-m", "pip", "freeze"],
        capture_output=True,
        text=True,
        check=True,
    )
    requirements: list[str] = []
    for line in (proc.stdout or "").splitlines():
        line = line.strip()
        if not line:
            continue
        # pip freeze emits "name==version"; skip the venv's own dists and
        # editable/egg entries which cannot be reinstalled offline.
        if line.startswith("-e ") or "@" in line.split("==")[0]:
            continue
        name = line.split("==")[0].strip()
        if name.lower().replace("_", "-") in {"pip", "setuptools", "wheel"}:
            continue
        requirements.append(line)

    with open(lock_path, "w", encoding="utf-8") as fh:
        fh.write("# shbuild lock file — resolved dependency set for this build.\n")
        fh.write(f"# Generated by `pip freeze` in the baked venv (python {version}).\n")
        for req in requirements:
            fh.write(req + "\n")

    return lock_path, requirements


def _pick_pip_interpreter(base_python: Path | str | None = None) -> str:
    """Choose an interpreter that has pip for running ``pip download``.

    Preference order: the caller-specified base (if it works), then the
    interpreter currently running shbuild, then bare ``python3`` on PATH. Any
    working pip suffices — we only use it to *download* wheels for the target
    platform, not to install into the payload venv.
    """
    import sys

    candidates: list[str] = []
    if base_python is not None:
        bp = Path(base_python)
        if bp.is_file():
            candidates.append(str(bp.resolve()))
    if sys.executable and Path(sys.executable).is_file():
        candidates.append(str(Path(sys.executable).resolve()))
    found = shutil.which("python3")
    if found:
        candidates.append(found)

    for cand in candidates:
        proc = subprocess.run(
            [cand, "-m", "pip", "--version"], capture_output=True, text=True
        )
        if proc.returncode == 0:
            return cand
    raise RuntimeError(f"no interpreter with pip available (tried: {candidates!r})")


def collect_wheels(
    staging_dir: Path,
    version: str,
    base_python: Path | None = None,
    requirements: list[str] | None = None,
) -> tuple[Path, list[Path]]:
    """Download prebuilt wheels for *requirements* into ``staging_dir/wheelhouse``.

    Wheels are resolved for the current (target) platform using pip's normal
    resolver — no venv is involved, so a plain interpreter suffices. The
    resulting directory can be embedded in the payload and used by the
    generated .sh to run an offline ``pip install --no-index`` on first launch.

    Args:
        staging_dir: Payload staging directory; wheels land in its
            ``wheelhouse/`` subdirectory.
        version: Python minor version string (e.g. "3.12"), used only to pick
            the interpreter binary if *base_python* is None.
        base_python: Absolute path of an interpreter with a working pip. When
            omitted, the current interpreter (sys.executable) is used — the
            wheels are for the target platform, not for the build venv.
        requirements: Requirement specs to resolve; when omitted, the pinned
            set from ``requirements.lock`` in *staging_dir* is used instead.

    Returns:
        ``(wheelhouse_dir, wheel_paths)`` — the staged directory and the list
        of downloaded ``.whl`` files (sorted by name).
    """
    if requirements is None:
        lock = staging_dir / "requirements.lock"
        if lock.is_file():
            requirements = [
                line.strip()
                for line in lock.read_text(encoding="utf-8").splitlines()
                if line.strip() and not line.startswith("#")
            ]
    if not requirements:
        raise ValueError("nothing to download: the resolved requirement set is empty")

    wheelhouse = staging_dir / "wheelhouse"
    if wheelhouse.exists():
        shutil.rmtree(wheelhouse)
    wheelhouse.mkdir(parents=True)

    py = _pick_pip_interpreter(base_python)
    proc = subprocess.run(
        [py, "-m", "pip", "download", "--no-deps", "--dest", str(wheelhouse), *requirements],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"failed to download wheels for {requirements!r}:\n{proc.stderr}")

    wheels = sorted(wheelhouse.glob("*.whl"))
    return wheelhouse, wheels


def build_wheelhouse(
    staging_dir: Path,
    venv_root: Path,
    version: str,
    base_python: Path | None = None,
) -> WheelhouseInfo:
    """Convenience wrapper: write the lock file AND bundle a wheelhouse.

    This is the one-call entry point used by fallback-mode builds. It records
    what the venv actually installed (the source of truth for the lock) and
    downloads matching wheels so first-run offline installation works even for
    dependencies that were not baked into the venv image itself.
    """
    lock_path, requirements = write_lock_file(staging_dir, venv_root, version)
    wheelhouse: Path | None = None
    wheels: list[Path] = []
    if requirements:
        wheelhouse, wheels = collect_wheels(
            staging_dir, version, base_python=base_python, requirements=requirements
        )
    return WheelhouseInfo(
        lock_path=lock_path,
        wheelhouse_dir=wheelhouse,
        locked_requirements=requirements,
        wheels=wheels,
    )


def needs_fallback(venv_root: Path, version: str) -> tuple[bool, list[str]]:
    """Detect whether the payload venv should carry a wheelhouse.

    A pure-Python dependency relocates perfectly inside the baked venv, so no
    fallback is needed. A dependency with compiled extension modules (``*.so``
    / ``*.pyd``) may rely on absolute paths or dynamic libraries that do not
    survive relocation to an arbitrary cache dir; for those we bundle wheels
    and let first run reinstall them offline via the embedded wheelhouse.

    Args:
        venv_root: Root of the (relocated) build venv.
        version: Python minor version string (e.g. "3.12").

    Returns:
        ``(required, ext_dists)`` — *required* is True when at least one
        installed distribution ships extension modules; *ext_dists* lists the
        names of those distributions (sorted, deduplicated).
    """
    sp = venv_root / "lib" / f"python{version}" / "site-packages"
    if not sp.is_dir():
        return False, []

    ext_dists: list[str] = []
    for dist_info in sorted(sp.glob("*.dist-info")):
        top_level = dist_info / "top_level.txt"
        names: list[str] = []
        if top_level.is_file():
            for line in top_level.read_text(encoding="utf-8").splitlines():
                name = line.strip()
                if name and not name.startswith(".") and "/" not in name:
                    names.append(name)
        else:
            # Fall back to a normalized dist name; the directory may still
            # exist under that spelling.
            names = [dist_info.name.split("-")[0].replace("-", "_")]

        for name in names:
            mod_dir = sp / name
            if not mod_dir.is_dir():
                continue
            has_ext = False
            for ext in ("*.so", "*.pyd"):
                if any(mod_dir.rglob(ext)):
                    has_ext = True
                    break
            if has_ext:
                dist_name = dist_info.name.split("-")[0]
                if dist_name not in ext_dists:
                    ext_dists.append(dist_name)

    return bool(ext_dists), sorted(ext_dists)


__all__ = [
    "WheelhouseInfo",
    "build_wheelhouse",
    "collect_wheels",
    "needs_fallback",
    "write_lock_file",
]
